[package]
name = "yui-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.3"
derive_more = "0.99.17"
is-even = "1.0.0"
itertools = "0.11.0"
num-bigint = "0.4.4"
num-traits = "0.2.16"
