[package]
name = "yui-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-even = "1.0.0"
num-bigint = "0.4.4"
num-traits = "0.2.16"
