[package]
name = "yui-kh"
description = "Khovanov Homology Library for YUI"
version = "0.5.0"

authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace  = true

[lib]
doctest = false

[features]
default = []
big-link = ["yui-link/big-link"]

[dependencies]
auto-impl-ops = "0.2.1"
delegate = "0.13.5"
derive_more = { version = "2.1.1", features = ["display", "debug"] }
log = "0.4.29"
maplit = "1.0.2"
num-traits = "0.2.19"
cfg-if = "1.0.4"
itertools = "0.15.0"
rustc-hash = "2.1.1"
rayon = "1.12.0"
dashmap = "6.1.0"
yui-core.workspace = true
yui-link.workspace = true
yui-matrix.workspace = true
yui-homology.workspace = true

[dev-dependencies]
yui-link = { workspace = true, features = ["test-utils"] }
yui-homology = { workspace = true, features = ["test-utils"] }
env_logger = "0.11"
