[package]
name = "yui-link"
description = ""

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
auto-impl-ops = "0.2.1"
delegate = "0.10.0"
derive_more = "0.99.17"
itertools = "0.11.0"
num-traits = "0.2.16"
regex = "1.10.2"
serde = "1.0.188"
serde_json = "1.0.107"

yui = { path = "../yui" }
