[package]
name = "yui-ratio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto-impl-ops = "0.2.1"
num-traits = "0.2.16"
regex = "1.9.6"

yui-core = { path = "../../yui" }
