[package]
name = "ykh"
description = "CLI for Khovanov Homology Computation"
version = "0.4.0"

authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace  = true

[features]
i128 = []
bigint = []
mimalloc = ["dep:mimalloc"]

[dependencies]
clap = { version = "4.6.1", features = ["derive", "cargo"] }
derive_more = { version = "2.1.1", features = ["display", "debug"] }
env_logger = "0.11.5"
log = "0.4.29"
num-bigint = "0.4.6"
num-traits = "0.2.19"
regex = "1.12.3"
serde_json = "1.0.149"
cfg-if = "1.0.4"
itertools = "0.14.0"
mimalloc = { version = "0.1", optional = true }
yui-core.workspace = true
yui-link.workspace = true
yui-matrix.workspace = true
yui-homology.workspace = true
yui-kh.workspace = true
smart-default = "0.7.1"

[dev-dependencies]
yui-link = { workspace = true, features = ["test-utils"] }
