use std::fmt::Display;

use ahash::RandomState;
use yui_core::{EucRing, EucRingOps, Ring, RingOps};

type IndexSet<X> = indexmap::IndexSet<X, RandomState>;
use yui_core::lc::{LcKey, Lc};
use yui_matrix::sparse::{SpMat, SpVec, Trans};


// Represents a free R-module generated by a finite set of elements in X. 

#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Summand<X, R>
where 
    X: LcKey,
    R: Ring, for<'x> &'x R: RingOps<R>
{
    raw_gens: IndexSet<X>,
    rank: usize, 
    tors: Vec<R>,
    trans: Trans<R>
}

impl<X, R> Summand<X, R>
where X: LcKey, R: Ring, for<'x> &'x R: RingOps<R> {
    pub fn new(raw_gens: IndexSet<X>, rank: usize, tors: Vec<R>, trans: Trans<R>) -> Self { 
        assert_eq!(trans.src_dim(), raw_gens.len());
        assert_eq!(trans.tgt_dim(), rank + tors.len());

        Self { raw_gens, rank, tors, trans }
    }

    pub fn from_raw_generators<Itr>(raw_gens: Itr) -> Self
    where Itr: IntoIterator<Item = X> {
        let gens = raw_gens.into_iter().collect::<IndexSet<X>>();
        let r = gens.len();
        Self::new(gens, r, vec![], Trans::id(r))
    }

    pub fn zero() -> Self {
        Self::new(IndexSet::default(), 0, vec![], Trans::zero())
    }

    pub fn rank(&self) -> usize {
        self.rank
    }

    pub fn tors(&self) -> &[R] {
        &self.tors
    }

    pub fn total_rank(&self) -> usize {
        self.rank + self.tors.len()
    }

    pub fn is_free(&self) -> bool {
        self.tors.is_empty()
    }

    pub fn is_zero(&self) -> bool {
        self.rank == 0 && self.is_free()
    }

    pub fn display(&self) -> String {
        crate::rmod_str(self.rank, &self.tors)
    }

    pub fn trans(&self) -> &Trans<R> {
        &self.trans
    }

    pub fn raw_generator(&self, i: usize) -> &X {
        &self.raw_gens[i]
    }

    pub fn raw_generators(&self) -> &IndexSet<X> {
        &self.raw_gens
    }

    pub fn generator(&self, i: usize) -> Lc<X, R> {
        let n = self.total_rank();
        let v = SpVec::unit(n, i);
        self.devectorize(&v)
    }

    pub fn generators(&self) -> impl Iterator<Item = Lc<X, R>> + use<'_, X, R> {
        (0 .. self.rank + self.tors.len()).map(|i| self.generator(i))
    }

    pub fn vectorize(&self, z: &Lc<X, R>) -> SpVec<R> {
        let n = self.raw_gens.len();

        // MEMO should add strict option. 

        let v = SpVec::from_entries(n, z.iter().flat_map(|(x, a)| { 
            self.raw_gens.get_index_of(x).map(|i| (i, a.clone()))
        }));

        self.trans.forward(&v)
    }

    pub fn vectorize_euc(&self, z: &Lc<X, R>) -> SpVec<R>
    where R: EucRing, for<'x> &'x R: EucRingOps<R> {
        let r = self.rank();
        let v = self.vectorize(z);

        SpVec::from_sorted_entries(v.dim(), v.iter().map(|(i, a)| { 
            if i < r { 
                (i, a.clone())
            } else { 
                let t = &self.tors()[i - r];
                (i, a % t)
            }
        }))
    }

    pub fn devectorize(&self, v: &SpVec<R>) -> Lc<X, R> {
        assert_eq!(v.dim(), self.total_rank());

        let v = self.trans.backward(v);

        Lc::from_iter( v.iter().map(|(i, a)| 
            (self.raw_gens[i].clone(), a.clone())
        ) )
    }

    pub fn make_matrix<Y, F>(&self, target: &Summand<Y, R>, map: F) -> SpMat<R>
    where Y: LcKey, F: Fn(&Lc<X, R>) -> Lc<Y, R> { 
        SpMat::from_col_vecs(target.total_rank(), self.generators().map(|z| {
            let w = map(&z);
            target.vectorize(&w)
        }))
    }

    pub fn make_matrix_euc<Y, F>(&self, target: &Summand<Y, R>, map: F) -> SpMat<R>
    where R: EucRing, for<'x> &'x R: EucRingOps<R>, Y: LcKey, F: Fn(&Lc<X, R>) -> Lc<Y, R> { 
        SpMat::from_col_vecs(target.total_rank(), self.generators().map(|z| {
            let w = map(&z);
            target.vectorize_euc(&w)
        }))
    }

    pub fn merge<Y>(&mut self, other: Summand<Y, R>)
    where Y: LcKey { 
        assert_eq!(self.trans.tgt_dim(), other.trans.src_dim());

        self.rank = other.rank;
        self.tors = other.tors.clone();
        self.trans.merge(other.trans);
        self.trans.reduce();
    }

    pub fn map_raw_generators<Y>(&self, f: impl Fn(&X) -> Y) -> Summand<Y, R>
    where Y: LcKey {
        Summand::new(
            self.raw_gens.iter().map(f).collect(),
            self.rank,
            self.tors.clone(),
            self.trans.clone()
        )
    }

    pub fn describe_generators(&self) -> String {
        use itertools::Itertools;
        self.generators().enumerate().map(|(i, x)| format!("{i}: {x}")).join("\n")
    }

    pub fn describe_raw_generators(&self) -> String {
        use itertools::Itertools;
        self.raw_gens.iter().enumerate().map(|(i, x)| format!("{i}: {x}")).join("\n")
    }

}

impl<X, R> Default for Summand<X, R>
where X: LcKey, R: Ring, for<'x> &'x R: RingOps<R> {
    fn default() -> Self {
        Self::zero()
    }
}

impl<X, R> Display for Summand<X, R>
where X: LcKey, R: Ring, for<'x> &'x R: RingOps<R> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.display().fmt(f)
    }
}

#[cfg(feature = "tex")]
mod tex { 
    use crate::tex_rmod_str;

    use super::*;
    use yui_core::TeX;

    impl<X, R> TeX for Summand<X, R>
    where X: LcKey, R: Ring + TeX, for<'x> &'x R: RingOps<R> {
        fn tex_math_symbol() -> String {
            "".to_string()
        }
    
        fn tex_string(&self) -> String {
            tex_rmod_str(self.rank(), self.tors())
        }
    }
}

#[cfg(test)]
mod tests { 
    use yui_core::lc::AsKey;

    use super::*;

    type X = AsKey<i32>;
    fn e(i: isize) -> X { 
        X::from(i as i32)
    }
    
    #[test]
    fn vectorize() { 
        let s = Summand::from_raw_generators([e(0), e(1), e(2)]);
        
        let x = Lc::from(e(0));
        let y = Lc::from(e(1));
        let z = Lc::from(e(2));

        let v = s.vectorize(&x);
        assert_eq!(v, SpVec::unit(3, 0));

        let v = s.vectorize(&(&x - &y * 2 + &z * 3));
        assert_eq!(v, SpVec::from(vec![1,-2,3]));
    }
        
    #[test]
    fn as_chain() { 
        let s = Summand::from_raw_generators([e(0), e(1), e(2)]);

        let x = Lc::from(e(0));
        let y = Lc::from(e(1));
        let z = Lc::from(e(2));

        let v = SpVec::from(vec![1, 2, -3]);
        let w = s.devectorize(&v);

        assert_eq!(w, &x + &y * 2 - &z * 3);
    }
}