[package]
name = "yui-homology"
description = ""

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = ["multithread"]
multithread = ["rayon"]
serde = ["dep:serde", "dep:serde_json", "ahash/serde"]
tex = ["yui/tex"]

[dependencies]
ahash = "0.8.11"
bimap = "0.6.3"
cartesian = "0.2.1"
cfg-if = "1.0.0"
delegate = "0.13.3"
derive_more = { version = "1.0.0", features = ["display", "debug", "add"] }
grouping_by = "0.2.2"
itertools = "0.13.0"
log = "0.4.27"
num-traits = "0.2.19"
rayon = { version = "1.10.0", optional = true }
serde = { version = "1.0.219", optional = true }
serde_json = { version = "1.0.140", optional = true }
sprs = "0.11.3"
yui = { path = "../yui" }
yui-matrix = { path = "../yui-matrix" }
